# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----

# ---- original file header ----
#
# @summary
#   Summarise what the function does here
#
Puppet::Functions.create_function(:'appstore_password') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
    hiera_password = lookupvar('appstore::password')
    appstore_user = lookupvar('appstore::appleid')

    command = "security -q find-generic-password -w -a #{appstore_user} -s 'Apple App Store'"

    if [:undefined, :undef, nil].include?(hiera_password)
      begin
        Puppet::Util::Execution.execute(command).to_str.strip
      rescue Puppet::ExecutionFailure => detail
        raise Puppet::ParseError, "Failed to lookup App Store password from keychain"
      end
    else
      hiera_password
    end
  
  end
end
