mod "boxen",       "3.6.2", :github_tarball => "boxen/puppet-boxen"
mod "stdlib",      "4.2.1", :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod "module-data", "0.0.1", :github_tarball => "ripienaar/puppet-module-data"
